# Generated by Django 3.2.9 on 2023-08-02 20:36

from django.db import migrations, models
import django.db.models.deletion
import virtualPantry_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('F', 'Fruit'), ('V', 'Vegetable'), ('G', 'Grains'), ('P', 'Protein'), ('D', 'Dairy'), ('O', 'Other')], max_length=1)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField(default=virtualPantry_app.models.one_week_hence)),
                ('food_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualPantry_app.foodlist')),
            ],
        ),
    ]
