# Generated by Django 3.2.9 on 2023-08-07 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualPantry_app', '0003_rename_food_product_productname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('F', 'Fruit'), ('V', 'Vegetable'), ('G', 'Grains'), ('P', 'Protein'), ('D', 'Dairy'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=250, unique=True)),
                ('recipe_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexName', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['expire_date']},
        ),
        migrations.AddField(
            model_name='recipedescription',
            name='recipeList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualPantry_app.recipeindex'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='ingredientList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualPantry_app.recipedescription'),
        ),
    ]
