# Generated by Django 3.2.9 on 2023-08-07 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualPantry_app', '0004_auto_20230807_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipedescription',
            old_name='recipe_description',
            new_name='recipe_instructions',
        ),
    ]
