# Generated by Django 3.2.9 on 2023-08-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualPantry_app', '0005_rename_recipe_description_recipedescription_recipe_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='category',
        ),
        migrations.AddField(
            model_name='recipedescription',
            name='recipeCategory',
            field=models.CharField(choices=[('b', 'Breakfast'), ('l', 'Lunch'), ('d', 'Dinner'), ('t', 'Desert'), ('s', 'Snack'), ('o', 'Other')], default='Other', max_length=1),
        ),
    ]
