# Generated by Django 3.2.9 on 2023-08-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualPantry_app', '0006_auto_20230807_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipedescription',
            old_name='recipeList',
            new_name='recipe_list',
        ),
    ]
