# Generated by Django 3.2.9 on 2023-08-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualPantry_app', '0007_rename_recipelist_recipedescription_recipe_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedescription',
            name='recipeCategory',
            field=models.CharField(choices=[('b', 'Breakfast'), ('l', 'Lunch'), ('d', 'Dinner'), ('t', 'Dessert'), ('s', 'Snack'), ('o', 'Other')], default='Other', max_length=1),
        ),
    ]
